server:
  port: 2222

spring:
  datasource:
    platform: postgres
    #url: jdbc:postgresql://<address>/<db_name>?sslmode=require
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update